version: "3.8"
services:
  db:
    image: mysql:8.0
    container_name: smallbiz_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: smallbiz
      MYSQL_USER: user
      MYSQL_PASSWORD: California~998
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3307:3306"
    volumes:
      ## backup sent to halwa_db_data for restoring purposes
      - ./smallbiz.sql:/docker-entrypoint-initdb.d/smallbiz.sql
      - halwa_db_data:/var/lib/mysql

  phpmyadmin:
    image: arm64v8/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root

volumes:
  ## ensures that data is never lost, even when rebuilding, prob not good for multiple containers?
  halwa_db_data:
